# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - comp7940chatbot1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_39539d811d1c4d9dae64aa4ecfb4dbeb }}
        password: ${{ secrets.AzureAppService_ContainerPassword_71f8a731954245919579f2940f5d7ae2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_39539d811d1c4d9dae64aa4ecfb4dbeb }}/comp7940chatbot/chatbotrepo:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'comp7940chatbot1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0c30f1305bab43248dd343d287bab9ca }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_39539d811d1c4d9dae64aa4ecfb4dbeb }}/comp7940chatbot/chatbotrepo:${{ github.sha }}'